# Default values for mychart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
imageBackend: junjie3617/csye7220backend:latest
backendUrl: http://ad0fd4d3d060b4a04a30b9d23ecfed3d-418243505.us-east-1.elb.amazonaws.com:8080

